version: '3.9'
services:
  apache1:
    image: httpd:latest
    volumes:
    - ./FRONTEND:/usr/local/apache2/htdocs
    ports:
    - "8081:80"

  nginx:
    image: nginx:latest
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "81:80"

  APIWeb:
    image: docker.io/bitnami/laravel:10
    volumes:
    - ./APIWeb/:/app
    environment:
    - DB_HOST=185.60.40.210
    - DB_PORT=3306
    - DB_USERNAME=Be単at
    - DB_PASSWORD=12345678
    - DB_DATABASE=Be単at
    ports:
    - "8085:8000"

  CapturaDatos:
    image: docker.io/bitnami/laravel:10
    volumes:
    - ./CapturaDatos/:/app
    environment:
    - DB_HOST=185.60.40.210
    - DB_PORT=3306
    - DB_USERNAME=Be単at
    - DB_PASSWORD=12345678
    - DB_DATABASE=Be単at
    ports:
    - "8086:8000"
    command: ["php", "artisan", "schedule:work"]