version: '3.2'
services:
  apache1:
    image: httpd:latest
    volumes:
    - ./home.html:/usr/local/apache2/htdocs/index.html
    ports:
    - "8081:80"

  nginx:
    image: nginx:latest
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "81:80"

  APIWeb:
    image: docker.io/bitnami/laravel:10
    volumes:
    - './APIWeb/:/app'
    ports:
    - "8085:80"
    